# Generated by Django 5.2.17 on 2026-08-24 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeClassroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_classroom', models.CharField(max_length=100, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('curso_classroom_id', models.CharField(max_length=100)),
                ('curso_nome', models.CharField(blank=True, max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_classroom', to='usuarios.usuario')),
            ],
        ),
    ]
