# Generated by Django 5.2.17 on 2026-08-18 05:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('ATIVIDADE', 'Atividade'), ('ESTUDO', 'Estudo'), ('PESSOAL', 'Pessoal'), ('OUTRO', 'Outro')], max_length=30)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('visibilidade', models.CharField(choices=[('PESSOAL', 'Apenas para mim'), ('TURMA', 'Para turma'), ('TODOS', 'Todos os alunos')], max_length=20)),
                ('turma', models.CharField(blank=True, max_length=100, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.usuario')),
            ],
        ),
    ]
