# Generated by Django 5.2.17 on 2026-08-17 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_suap', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('matricula', models.CharField(blank=True, max_length=30)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('curso', models.CharField(blank=True, max_length=150)),
                ('turma', models.CharField(blank=True, max_length=100)),
                ('foto', models.URLField(blank=True)),
            ],
        ),
    ]
